# Generated by Django 3.0.7 on 2020-12-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='documents')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_original_price', models.IntegerField()),
                ('product_discounted_price', models.IntegerField()),
                ('product_image_1', models.ImageField(upload_to='documents')),
                ('product_image_2', models.ImageField(upload_to='documents')),
                ('product_image_3', models.ImageField(upload_to='documents')),
                ('product_discription', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('product_brands', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.Brands')),
                ('product_category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.Category')),
                ('product_sub_category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.Sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, default='', to='eshop.Sub_category'),
        ),
    ]
