# Generated by Django 3.0.7 on 2020-12-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='sub_category_image',
            field=models.ImageField(default='', upload_to='documents'),
            preserve_default=False,
        ),
    ]
