# Generated by Django 3.0.7 on 2020-12-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_sub_category_sub_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_brands',
        ),
    ]
