# Generated by Django 3.0.7 on 2020-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20201230_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ManyToManyField(blank=True, default='', to='eshop.Brands'),
        ),
    ]
