# Generated by Django 3.0.7 on 2020-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_product_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='category',
            field=models.ManyToManyField(blank=True, default='', to='eshop.Category'),
        ),
    ]
