# Generated by Django 3.0.7 on 2020-12-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20201231_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
