# Generated by Django 3.0.7 on 2021-01-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activte',
            field=models.BooleanField(default=False),
        ),
    ]
