# Generated by Django 3.0.7 on 2021-01-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_customer_activte'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(default=' ', max_length=6),
            preserve_default=False,
        ),
    ]
