# Generated by Django 3.1.5 on 2021-01-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.cart')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.product')),
            ],
        ),
    ]
